title: My Food Blog
author: Zeenat
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Here I talka bout my experiences with food from around the world.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
